name: Docker Dev Images Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
    

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker-build-workflow.yaml
    with:
      tag: latest